# -----------------------------
# Reproducibility and resources
# -----------------------------
max_threads: 18

batching:
  "25_50": 1
  # "10_25": 1

# -----------------------------
# Curated FASTA inputs
# -----------------------------
curated_fastas:
  "25_50": "data/curated_md-lais/25_50/alls_RangeSelected_25_50_curado.fasta"
 #"10_25": "data/curated_md-lais/10_25/alls_RangeSelected_10_25_curado.fasta"

# -----------------------------
# Pre-processing: MMseqs2 clustering
# -----------------------------
mmseqs:
  min_seq_id: 0.95
  coverage: 0.8
  cov_mode: 1
  sensitivity: 7.5
  sub_mat: "aa:blosum62.out,nucl:nucleotide.out"
# -----------------------------
# Tox_check: 
# -----------------------------
toxteller:
  program_dir: "resources/ToxTeller/"

captp:
  program_dir: "resources/CAPTP/"
